title: Juan's Portfolio
iconURL: assets/image.png
#theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  linkedin: juan-camilo-jojoa-sanchez-956212116/
  github: juanjjs

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
